services:
  postgresdb:
    build:
      context: .
      dockerfile: docker/postgres.Dockerfile
    restart: on-failure
    env_file: ./.env
    ports:
      - "5433:5432"
    volumes:
      - db:/var/lib/postgresql/data

  express-server:
    depends_on:
      - postgresdb
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    env_file: ./.env
    ports:
      - "${PORT}:${PORT}"
    stdin_open: true
    tty: true

volumes:
  db:
